[mw_genie_newest]
title = "지니 ─ 최신음악"
url = "http://mw.genie.co.kr/newest"
entrySelector = "ul.list-album li"
titleSelector = "a div.info p.album-title.ellipsis"
linkSelector = "a"
contentSelector = "a div.info span.artist.text-gray.ellipsis"
imageSelector = "a div.thumbnail img"
waitUntil = "networkidle"